# Program utama
> Program ini akan merekomendasikan SAHAM-SAHAM yang beberapa hari kedepan insya allah akan NAIK

In [1]:
# ~~~~~ 1. tentukan tanggal
from datetime import date
today = date.today() #metode untuk mendapatkan tanggal lokal saat ini.
hari_ini = today.strftime("%Y%m%d")# mengambil tanggal hari ini. (untuk nama file)

# # tanggal mulai input model memprediksi
# mulai_ipred = '2021-10-01'
# # tanggal akhir input model memprediksi
# akhir_ipred = today.strftime("%Y-%m-%d") #metode strftime() untuk membuat string yang mewakili tanggal dalam format yang berbeda.

# berapa hari kedepan kita ingin memprediksi 
h_predik = 3 #hari

# email
login_email = 'xxx@gmail.com' # email untuk masuk ke akun
login_pass_txt = 'data/password.txt' # password email tadi untuk masuk ke akun
email_pengirim = 'xxx@gmail.com' # email pengirim
# siapa saja yang akan menerima emailnya
list_penerima_email = ['xxx@gmail.com']#jika nambah harus pake spasi sesudah koma

# bisi mau memprediksi kapanpun itu
mulai_ipred = '2021-05-01'
akhir_ipred = '2022-05-20'

In [2]:
from fungsi import makanan, cocok
# ~~~~~ 2. file yang berisi ticker jadikan sebuah list
# file_ticker_txt = 'data/ticker_issi.txt'
# with open(file_ticker_txt) as file:
#     ticker = file.readlines()
#     list_ticker = [line.rstrip() for line in ticker]

list_ticker = cocok.ticker_sama('data/ticker_issi.txt','data/jii70_20220222.txt')
# ~~~~~ 3. mengambil dan menyimpan data saham untuk input model memprediksi
# makanan.psaham(mulai_ipred,akhir_ipred,list_ticker)
print("makanan ai selesai")

# ~~~~~ 4. saatnya para AI melakukan tugasnya
# ini menghasilkan dataframe yang berisi saham yang naik
from fungsi import pake_kk
hasil_k1 = pake_kk.pake_k1(list_ticker,h_predik)# kelas 1
hasil_k2 = pake_kk.pake_k2(list_ticker,h_predik)# kelas 2
hasil_k3 = pake_kk.pake_k3(list_ticker,h_predik)# kelas 3
hasil_k4 = pake_kk.pake_k4(list_ticker,h_predik)# kelas 4
hasil_k5 = pake_kk.pake_k5(list_ticker,h_predik)# kelas 5
hasil_k6 = pake_kk.pake_k6(list_ticker,h_predik)# kelas 6
hasil_k7 = pake_kk.pake_k7(list_ticker,h_predik)# kelas 7
hasil_k8 = pake_kk.pake_k8(list_ticker,h_predik)# kelas 8
hasil_k9 = pake_kk.pake_k9(list_ticker,h_predik)# kelas 9
hasil_k10 = pake_kk.pake_k10(list_ticker,h_predik)# kelas 10
hasil_k11 = pake_kk.pake_k11(list_ticker,h_predik)# kelas 11
hasil_k12 = pake_kk.pake_k12(list_ticker,h_predik)# kelas 12
hasil_k13 = pake_kk.pake_k13(list_ticker,h_predik)# kelas 13
hasil_k14 = pake_kk.pake_k14(list_ticker,h_predik)# kelas 14
hasil_k15 = pake_kk.pake_k15(list_ticker,h_predik)# kelas 15
hasil_k16 = pake_kk.pake_k16(list_ticker,h_predik)# kelas 16
hasil_k17 = pake_kk.pake_k17(list_ticker,h_predik)# kelas 17
hasil_k18 = pake_kk.pake_k18(list_ticker,h_predik)# kelas 18
hasil_k19 = pake_kk.pake_k19(list_ticker,h_predik)# kelas 19
hasil_k20 = pake_kk.pake_k20(list_ticker,h_predik)# kelas 20
hasil_k21 = pake_kk.pake_k21(list_ticker,h_predik)# kelas 21

makanan ai selesai
WARNING:tensorflow:5 out of the last 13 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001A9F8203400> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 13 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001A9FD9B8040> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Kelas 1 selesai
Kelas 2 selesai
Kelas 3 selesai
Kelas 4 selesai
Kelas 5 selesai
Kelas 6 selesai
Kelas 7 selesai
Kelas 8 selesai
Kelas 9 selesai
Kelas 10 selesai
Kelas 11 selesai
Kelas 12 selesai
Kelas 13 selesai
Kelas 14 selesai
Kelas 15 selesai
Kelas 16 selesai
Kelas 17 selesai
Kelas 18 selesai
Kelas 19 selesai
Kelas 20 selesai
Kelas 21 selesai

In [3]:
# ~~~~~ 5. mengambil voting peringkat 3 , 5, dan 10 besar
# 3 besar
from fungsi import voting3
peringkat3_besar = voting3.peringkat_3(hasil_k1,hasil_k2,hasil_k3,hasil_k4,hasil_k5,
                                      hasil_k6,hasil_k7,hasil_k8,hasil_k9,hasil_k10,
                                      hasil_k11,hasil_k12,hasil_k13,hasil_k14,hasil_k15,
                                      hasil_k16,hasil_k17,hasil_k18,hasil_k19,hasil_k20,
                                      hasil_k21)
# 5 besar
peringkat5_besar = voting3.peringkat_5(hasil_k1,hasil_k2,hasil_k3,hasil_k4,hasil_k5,
                                      hasil_k6,hasil_k7,hasil_k8,hasil_k9,hasil_k10,
                                      hasil_k11,hasil_k12,hasil_k13,hasil_k14,hasil_k15,
                                      hasil_k16,hasil_k17,hasil_k18,hasil_k19,hasil_k20,
                                      hasil_k21)
# 10 besar
peringkat10_besar = voting3.peringkat_10(hasil_k1,hasil_k2,hasil_k3,hasil_k4,hasil_k5,
                                      hasil_k6,hasil_k7,hasil_k8,hasil_k9,hasil_k10,
                                      hasil_k11,hasil_k12,hasil_k13,hasil_k14,hasil_k15,
                                      hasil_k16,hasil_k17,hasil_k18,hasil_k19,hasil_k20,
                                      hasil_k21)
# ~~~~~ 6. Mengambil keputusan untuk hasil akhir
from fungsi import harga, beli_saham
pembelian = harga.pembelian(peringkat3_besar)
beli_saham.beli_saham(pembelian, h_predik)

     Saham-saham yang akan naik 3 hari kedepan:
1. Saham AGII
   - Harga terakhir saham AGII = Rp 1975.0
   - Harga saham AGII  di 1% = Rp 1994.75
   - Harga batas saham AGII di 2% = Rp 2014.5
   - Harga 1 lot saham AGII di 2% = Rp 201450
Beli disekitar harga 1975.0 sampai 2014.5.  **jika bisa lebih kurang dari itu, maka akan lebih bagus

2. Saham FILM
   - Harga terakhir saham FILM = Rp 1375.0
   - Harga saham FILM  di 1% = Rp 1388.75
   - Harga batas saham FILM di 2% = Rp 1402.5
   - Harga 1 lot saham FILM di 2% = Rp 140250
Beli disekitar harga 1375.0 sampai 1402.5.  **jika bisa lebih kurang dari itu, maka akan lebih bagus

!!!!! JANGAN SAMPAI KESINI !!!!!
~ Harga Maksimal pembelian saham AGII di 5% = Rp 2073.75
~ Harga Maksimal pembelian saham FILM di 5% = Rp 1443.75

In [4]:
peringkat3_besar

  Saham voting total jumlah persentase(%)
0  AGII     11                  38.002153
1  FILM      7                  17.988011
2  HRUM      5                  10.098658
3  INCO      5                  19.518844
4  UNVR      4                  12.291542
5  LPKR      4                   7.858921
6  BANK      3                   5.200442
7  UNTR      2                    3.94766
8  KAEF      2                   2.156393
9  ICBP      2                   2.796217

In [5]:
peringkat5_besar

   Saham voting total jumlah persentase(%)
0   AGII     11                  38.002153
1   LPKR      9                   15.19933
2   HRUM      8                  14.142623
3   FILM      8                  19.079222
4   UNVR      6                   15.07209
5   INCO      6                   21.87095
6   LSIP      4                   4.464047
7   ITMG      4                   5.047264
8   SIDO      3                   4.648741
9   CPIN      3                    5.29673
10  ICBP      3                   3.786495
11  KPIG      3                   5.836592
12  BANK      3                   5.200442
13  AALI      3                   6.077772
14  PGAS      2                   2.362751
15  PTBA      2                   1.463568
16  TAPG      2                   2.245266
17  TINS      2                   3.520848
18  UNTR      2                    3.94766
19  MLPL      2                   3.745002
20  KAEF      2                   2.156393

In [6]:
peringkat10_besar.to_csv(f'hasil_Rizky/{hari_ini}_10besar.csv',index=False)
peringkat10_besar

   Saham voting total jumlah persentase(%)
0   LPKR     16                  22.109714
1   HRUM     14                  19.064547
2   AGII     11                  38.002153
3   UNVR     10                  19.550633
4   FILM     10                  21.301719
5   INCO      9                  24.214225
6   LSIP      9                  10.992808
7   AALI      8                  10.084903
8   PTBA      7                   6.599297
9   ITMG      6                    6.74226
10  TAPG      6                   6.437463
11  CPIN      6                   7.367931
12  KPIG      6                   8.101852
13  SIDO      5                   6.374813
14  KAEF      5                   4.529076
15  UNTR      5                    7.35904
16  ICBP      5                   6.663169
17  TINS      5                   7.091554
18  PGAS      4                    3.84088
19  BANK      4                   6.289204
20  ASRI      3                   3.915971
21  ISAT      3                   6.990739
22  ELSA      3                   2.459103
23  LPPF      3                   2.447884
24  MIKA      3                   2.403453
25  ANTM      2                   6.153942
26  BRPT      2                   2.215724
27  MLPL      2                   3.745002
28  SMRA      2                   1.403903
29  INTP      2                    1.62533
30  PTPP      2                   2.142617
31  AKRA      2                   1.848492
32  EXCL      2                   2.308649
33  RALS      2                   3.236094
34  TPIA      2                   5.833301
35  ADRO      2                   1.868386
36  MYOR      2                   4.026113

In [7]:
# ~~~~~ 7. Mengirim hasilnya ke email
from fungsi import email
email.kirim_email(login_email,login_pass_txt,email_pengirim,list_penerima_email,
                  pembelian,peringkat3_besar,peringkat5_besar,h_predik)

TypeError: kirim_email() missing 2 required positional arguments: 'h_predik' and 'tgl_akhir_data'

# Ini dipakai hanya jika diperingkat 3,5,dan 10 tidak ada saham yang sama

In [ ]:
# mengambil_voting = voting.pemungutan_suara(hasil_k1,hasil_k2,hasil_k3,hasil_k4,hasil_k5,hasil_k6,hasil_k7,
#                                          hasil_k8,hasil_k9,hasil_k10,hasil_k11,hasil_k12,hasil_k13,hasil_k14,
#                                          hasil_k15,hasil_k16,hasil_k17,hasil_k18,hasil_k19,hasil_k20,hasil_k21)
# mengambil_voting.to_csv(f'hasil_Rizky/{hari_ini}_voting.csv',index=False)
# mengambil_voting