# Program utama
> Program ini akan merekomendasikan SAHAM-SAHAM yang beberapa hari kedepan insya allah akan NAIK

In [9]:
# ~~~~~ 1. tentukan tanggal
from datetime import date
today = date.today() #metode untuk mendapatkan tanggal lokal saat ini.
hari_ini = today.strftime("%Y%m%d")# mengambil tanggal hari ini. (untuk nama file)

# # tanggal mulai input model memprediksi
# mulai_ipred = '2021-10-01'
# # tanggal akhir input model memprediksi
# akhir_ipred = today.strftime("%Y-%m-%d") #metode strftime() untuk membuat string yang mewakili tanggal dalam format yang berbeda.

# berapa hari kedepan kita ingin memprediksi 
h_predik = 3 #hari

# email
login_email = 'xxx@gmail.com' # email untuk masuk ke akun
login_pass_txt = 'data/password.txt' # password email tadi untuk masuk ke akun
email_pengirim = 'xxx@gmail.com' # email pengirim
# siapa saja yang akan menerima emailnya
list_penerima_email = ['xxx@gmail.com']#jika nambah harus pake spasi sesudah koma

# bisi mau memprediksi kapanpun itu
mulai_ipred = '2021-05-01'
akhir_ipred = '2022-04-21'

In [10]:
from fungsi import makanan, voting, cocok
# ~~~~~ 2. file yang berisi ticker jadikan sebuah list
# file_ticker_txt = 'data/ticker_issi.txt'
# with open(file_ticker_txt) as file:
#     ticker = file.readlines()
#     list_ticker = [line.rstrip() for line in ticker]

list_ticker = cocok.ticker_sama('data/ticker_issi.txt','data/jii30_20220222.txt')
# ~~~~~ 3. mengambil dan menyimpan data saham untuk input model memprediksi
# makanan.psaham(mulai_ipred,akhir_ipred,list_ticker)
print("makanan ai selesai")

# ~~~~~ 4. saatnya para AI melakukan tugasnya
# ini menghasilkan dataframe yang berisi saham yang naik
from fungsi import pake_kk
hasil_k1 = pake_kk.pake_k1(list_ticker,h_predik)# kelas 1
hasil_k2 = pake_kk.pake_k2(list_ticker,h_predik)# kelas 2
hasil_k3 = pake_kk.pake_k3(list_ticker,h_predik)# kelas 3
hasil_k4 = pake_kk.pake_k4(list_ticker,h_predik)# kelas 4
hasil_k5 = pake_kk.pake_k5(list_ticker,h_predik)# kelas 5
hasil_k6 = pake_kk.pake_k6(list_ticker,h_predik)# kelas 6
hasil_k7 = pake_kk.pake_k7(list_ticker,h_predik)# kelas 7
hasil_k8 = pake_kk.pake_k8(list_ticker,h_predik)# kelas 8
hasil_k9 = pake_kk.pake_k9(list_ticker,h_predik)# kelas 9
hasil_k10 = pake_kk.pake_k10(list_ticker,h_predik)# kelas 10
hasil_k11 = pake_kk.pake_k11(list_ticker,h_predik)# kelas 11
hasil_k12 = pake_kk.pake_k12(list_ticker,h_predik)# kelas 12
hasil_k13 = pake_kk.pake_k13(list_ticker,h_predik)# kelas 13
hasil_k14 = pake_kk.pake_k14(list_ticker,h_predik)# kelas 14
hasil_k15 = pake_kk.pake_k15(list_ticker,h_predik)# kelas 15
hasil_k16 = pake_kk.pake_k16(list_ticker,h_predik)# kelas 16
hasil_k17 = pake_kk.pake_k17(list_ticker,h_predik)# kelas 17
hasil_k18 = pake_kk.pake_k18(list_ticker,h_predik)# kelas 18
hasil_k19 = pake_kk.pake_k19(list_ticker,h_predik)# kelas 19
hasil_k20 = pake_kk.pake_k20(list_ticker,h_predik)# kelas 20
hasil_k21 = pake_kk.pake_k21(list_ticker,h_predik)# kelas 21

makanan ai selesai
WARNING:tensorflow:5 out of the last 15 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000214C964F370> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 13 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000214C962A5F0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Kelas 1 selesai
Kelas 2 selesai
Kelas 3 selesai
Kelas 4 selesai
Kelas 5 selesai
Kelas 6 selesai
Kelas 7 selesai
Kelas 8 selesai
Kelas 9 selesai
Kelas 10 selesai
Kelas 11 selesai
Kelas 12 selesai
Kelas 13 selesai
Kelas 14 selesai
Kelas 15 selesai
Kelas 16 selesai
Kelas 17 selesai
Kelas 18 selesai
Kelas 19 selesai
Kelas 20 selesai
Kelas 21 selesai

In [11]:
# ~~~~~ 5. mengambil voting peringkat 3 , 5, dan 10 besar
# 3 besar
peringkat3_besar = voting.peringkat_3(hasil_k1,hasil_k2,hasil_k3,hasil_k4,hasil_k5,
                                      hasil_k6,hasil_k7,hasil_k8,hasil_k9,hasil_k10,
                                      hasil_k11,hasil_k12,hasil_k13,hasil_k14,hasil_k15,
                                      hasil_k16,hasil_k17,hasil_k18,hasil_k19,hasil_k20,
                                      hasil_k21)
# 5 besar
peringkat5_besar = voting.peringkat_5(hasil_k1,hasil_k2,hasil_k3,hasil_k4,hasil_k5,
                                      hasil_k6,hasil_k7,hasil_k8,hasil_k9,hasil_k10,
                                      hasil_k11,hasil_k12,hasil_k13,hasil_k14,hasil_k15,
                                      hasil_k16,hasil_k17,hasil_k18,hasil_k19,hasil_k20,
                                      hasil_k21)
# 10 besar
peringkat10_besar = voting.peringkat_10(hasil_k1,hasil_k2,hasil_k3,hasil_k4,hasil_k5,
                                      hasil_k6,hasil_k7,hasil_k8,hasil_k9,hasil_k10,
                                      hasil_k11,hasil_k12,hasil_k13,hasil_k14,hasil_k15,
                                      hasil_k16,hasil_k17,hasil_k18,hasil_k19,hasil_k20,
                                      hasil_k21)
# ~~~~~ 6. Mengambil keputusan untuk hasil akhir
from fungsi import harga, beli_saham
pembelian = harga.pembelian(peringkat3_besar)
beli_saham.beli_saham(pembelian, h_predik)

     Saham-saham yang akan naik 3 hari kedepan:
1. Saham INCO
   - Harga terakhir saham INCO = Rp 8000.0
   - Harga batas saham INCO di 2% = Rp 8160.0
   - Harga 1 lot batas saham INCO di 2% = Rp 816000
Beli disekitar harga 8000.0 sampai 8160.0.  **jika bisa lebih kurang dari itu, maka akan lebih bagus

2. Saham EXCL
   - Harga terakhir saham EXCL = Rp 3240.0
   - Harga batas saham EXCL di 2% = Rp 3304.8
   - Harga 1 lot batas saham EXCL di 2% = Rp 330480
Beli disekitar harga 3240.0 sampai 3304.8.  **jika bisa lebih kurang dari itu, maka akan lebih bagus

!!!!! JANGAN SAMPAI KESINI !!!!!
~ Harga Maksimal pembelian saham INCO di 5% = Rp 8400.0
~ Harga Maksimal pembelian saham EXCL di 5% = Rp 3402.0

In [12]:
peringkat3_besar

  Saham voting total jumlah persentase(%)
0  INCO      6                  29.396105
1  EXCL     12                  21.450167
2  EMTK      6                  12.831732
3  MNCN     10                  12.610124
4  TINS      4                   7.307941
5  BRPT      4                    6.21801
6  ICBP      2                   4.195765
7  UNTR      2                   2.702457
8  UNVR      2                    1.98065
9  PGAS      2                   1.283688

In [13]:
peringkat5_besar

   Saham voting total jumlah persentase(%)
0   INCO      6                  29.396105
1   EXCL     12                  21.450167
2   EMTK      9                  15.620716
3   MNCN     12                  14.933199
4   BRPT      8                   9.364656
5   TINS      4                   7.307941
6   WIKA      8                   6.739644
7   ICBP      4                   6.049387
8   UNTR      4                   4.655317
9   UNVR      5                   4.653782
10  MIKA      4                   4.321332
11  PTBA      4                   4.264273
12  PGAS      7                   4.253409
13  ADRO      2                   3.136889
14  TPIA      2                   2.475243
15  BRIS      3                   2.295601
16  ITMG      2                   1.958265
17  KLBF      2                   0.935971

In [14]:
peringkat10_besar.to_csv(f'hasil_Rizky/{hari_ini}_10besar.csv',index=False)
peringkat10_besar

   Saham voting total jumlah persentase(%)
0   INCO      9                  29.979693
1   EXCL     15                  22.817333
2   EMTK     10                  15.916271
3   MNCN     14                  15.560698
4   BRPT     15                  11.803403
5   WIKA     15                   10.40774
6   ICBP     12                   8.624364
7   TINS      8                   8.619436
8   PGAS     13                   7.412317
9   PTBA     10                   6.838048
10  UNTR      6                   5.880595
11  UNVR      7                   5.840313
12  BRIS     11                   5.486138
13  MIKA      6                   5.088722
14  ADRO      4                   4.347614
15  TPIA      6                   3.939275
16  ERAA      3                    3.87887
17  ITMG      4                   3.502589
18  PTPP      7                   3.333735
19  ANTM      3                   2.940541
20  INDF      9                     2.6768
21  KLBF      5                   2.168288
22  INTP      5                   1.701989
23  SMGR      4                   1.617625
24  JPFA      2                   1.265826
25  CPIN      2                   1.091037
26  TKIM      3                   0.943255

In [15]:
# ~~~~~ 7. Mengirim hasilnya ke email
from fungsi import email
email.kirim_email(login_email,login_pass_txt,email_pengirim,list_penerima_email,
                  pembelian,peringkat3_besar,peringkat5_besar,h_predik)

# Ini dipakai hanya jika diperingkat 3,5,dan 10 tidak ada saham yang sama

In [16]:
# mengambil_voting = voting.pemungutan_suara(hasil_k1,hasil_k2,hasil_k3,hasil_k4,hasil_k5,hasil_k6,hasil_k7,
#                                          hasil_k8,hasil_k9,hasil_k10,hasil_k11,hasil_k12,hasil_k13,hasil_k14,
#                                          hasil_k15,hasil_k16,hasil_k17,hasil_k18,hasil_k19,hasil_k20,hasil_k21)
# mengambil_voting.to_csv(f'hasil_Rizky/{hari_ini}_voting.csv',index=False)
# mengambil_voting