# Program utama2
> Program ini akan merekomendasikan SAHAM-SAHAM yang beberapa hari kedepan insya allah akan NAIK

In [10]:
# ~~~~~ 1. tentukan tanggal
from datetime import date
today = date.today() #metode untuk mendapatkan tanggal lokal saat ini.
hari_ini = today.strftime("%Y%m%d")# mengambil tanggal hari ini. (untuk nama file)

# # tanggal mulai input model memprediksi
# mulai_ipred = '2021-10-01'
# # tanggal akhir input model memprediksi
# akhir_ipred = today.strftime("%Y-%m-%d") #metode strftime() untuk membuat string yang mewakili tanggal dalam format yang berbeda.

# berapa hari kedepan kita ingin memprediksi 
h_predik = 3 #hari

# email
login_email = 'xxx@gmail.com' # email untuk masuk ke akun
login_pass_txt = 'data/password.txt' # password email tadi untuk masuk ke akun
email_pengirim = 'xxx@gmail.com' # email pengirim
# siapa saja yang akan menerima emailnya
list_penerima_email = ['xxx@gmail.com']#jika nambah harus pake spasi sesudah koma

# bisi mau memprediksi kapanpun itu
mulai_ipred = '2021-05-01'
akhir_ipred = '2022-04-21'

In [11]:
from fungsi import makanan, voting2, cocok
# ~~~~~ 2. file yang berisi ticker jadikan sebuah list
# file_ticker_txt = 'data/ticker_issi.txt'
# with open(file_ticker_txt) as file:
#     ticker = file.readlines()
#     list_ticker = [line.rstrip() for line in ticker]

list_ticker = cocok.ticker_sama('data/ticker_issi.txt','data/jii30_20220222.txt')
# ~~~~~ 3. mengambil dan menyimpan data saham untuk input model memprediksi
# makanan.psaham(mulai_ipred,akhir_ipred,list_ticker)
print("makanan ai selesai")

# ~~~~~ 4. saatnya para AI melakukan tugasnya
# ini menghasilkan dataframe yang berisi saham yang naik
from fungsi import pake_kk
hasil_k2 = pake_kk.pake_k2(list_ticker,h_predik)# kelas 2
hasil_k5 = pake_kk.pake_k5(list_ticker,h_predik)# kelas 5
hasil_k6 = pake_kk.pake_k6(list_ticker,h_predik)# kelas 6
hasil_k9 = pake_kk.pake_k9(list_ticker,h_predik)# kelas 9
hasil_k12 = pake_kk.pake_k12(list_ticker,h_predik)# kelas 12
hasil_k16 = pake_kk.pake_k16(list_ticker,h_predik)# kelas 16
hasil_k17 = pake_kk.pake_k17(list_ticker,h_predik)# kelas 17
hasil_k18 = pake_kk.pake_k18(list_ticker,h_predik)# kelas 18
hasil_k20 = pake_kk.pake_k20(list_ticker,h_predik)# kelas 20

makanan ai selesai
WARNING:tensorflow:5 out of the last 15 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000013B63DDFC70> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 13 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000013B6D010160> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Kelas 2 selesai
Kelas 5 selesai
Kelas 6 selesai
Kelas 9 selesai
Kelas 12 selesai
Kelas 16 selesai
Kelas 17 selesai
Kelas 18 selesai
Kelas 20 selesai

In [12]:
# ~~~~~ 5. mengambil voting peringkat 3 , 5, dan 10 besar
from fungsi import voting2
# 1 besar
peringkat1_besar = voting2.peringkat_1(hasil_k2,hasil_k5,hasil_k6,hasil_k9,hasil_k12,
                                      hasil_k16,hasil_k17,hasil_k18,hasil_k20)
# 3 besar
peringkat3_besar = voting2.peringkat_3(hasil_k2,hasil_k5,hasil_k6,hasil_k9,hasil_k12,
                                      hasil_k16,hasil_k17,hasil_k18,hasil_k20)
# 5 besar
peringkat5_besar = voting2.peringkat_5(hasil_k2,hasil_k5,hasil_k6,hasil_k9,hasil_k12,
                                      hasil_k16,hasil_k17,hasil_k18,hasil_k20)
# 10 besar
peringkat10_besar = voting2.peringkat_10(hasil_k2,hasil_k5,hasil_k6,hasil_k9,hasil_k12,
                                      hasil_k16,hasil_k17,hasil_k18,hasil_k20)
# ~~~~~ 6. Mengambil keputusan untuk hasil akhir
from fungsi import harga, beli_saham
pembelian = harga.pembelian(peringkat1_besar)
# beli_saham.beli_saham(pembelian, h_predik)

In [13]:
peringkat1_besar

  Saham voting total jumlah persentase(%)
0  INCO      2                  13.861225
1  EXCL      2                   5.008507

In [14]:
peringkat3_besar

  Saham voting total jumlah persentase(%)
0  EXCL      5                   9.129866
1  INCO      3                   15.16626
2  MNCN      3                   3.152091
3  EMTK      2                   3.174664
4  BRPT      2                   4.103223
5  ICBP      2                   4.195765

In [15]:
peringkat5_besar

   Saham voting total jumlah persentase(%)
0   MNCN      5                   5.475166
1   EXCL      5                   9.129866
2   BRPT      4                   5.574507
3   UNVR      4                    4.06769
4   ICBP      4                   6.049387
5   WIKA      3                   2.131077
6   INCO      3                   15.16626
7   EMTK      3                   3.635085
8   PGAS      3                    1.48911
9   TPIA      2                   2.475243
10  ADRO      2                   3.136889

In [16]:
peringkat10_besar.to_csv(f'hasil_Rizky/{hari_ini}_10besar.csv',index=False)
peringkat10_besar

   Saham voting total jumlah persentase(%)
0   EXCL      7                  10.175229
1   BRPT      7                   6.149842
2   WIKA      7                   4.191507
3   ICBP      7                   7.031231
4   PGAS      6                   3.193319
5   MNCN      6                   5.851097
6   UNVR      5                   4.725515
7   INCO      4                  15.223524
8   EMTK      4                    3.93064
9   PTPP      4                   1.968448
10  TPIA      3                   2.832457
11  INDF      3                   0.628112
12  BRIS      3                   0.815253
13  PTBA      3                   1.502776
14  TINS      3                   3.894686
15  TKIM      2                   0.596179
16  SMGR      2                   0.663511
17  CPIN      2                   1.091037
18  ADRO      2                   3.136889
19  UNTR      2                    2.26648
20  MIKA      2                    0.47396
21  ITMG      2                   1.544324

In [17]:
# ~~~~~ 7. Mengirim hasilnya ke email
from fungsi import email
email.kirim_email(login_email,login_pass_txt,email_pengirim,list_penerima_email,
                  pembelian,peringkat1_besar,peringkat5_besar,h_predik)

# Ini dipakai hanya jika diperingkat 3,5,dan 10 tidak ada saham yang sama

In [18]:
# mengambil_voting = voting.pemungutan_suara(hasil_k2,hasil_k5,hasil_k6,hasil_k9,hasil_k12,
#                                       hasil_k16,hasil_k17,hasil_k18,hasil_k20)
# mengambil_voting.to_csv(f'hasil_Rizky/{hari_ini}_voting.csv',index=False)
# mengambil_voting